---
title: "Invenage boot check"
author: "Cuong Do"
date: "6/20/2021"
output: html_document
---

```{r setup, echo=T}
knitr::opts_chunk$set(echo = TRUE)
config_dict <- read.csv(file.path(path.expand("~"),'invenage','config.csv'))
app_path <- gsub(';','/',config_dict$value[config_dict$name=='app_path'])
source(file.path(app_path,'admin1_ui','global.R'))
```

### Boot check

We first check for data type inconsistency, if a column name has different data types in different table it will be listed here.

```{r data_type_check}
conn <- db_open(config_dict)
tmp <- dbGetQuery(conn,'SELECT * FROM INFORMATION_SCHEMA.COLUMNS')
dbDisconnect(conn)
tmp <- tmp[tmp$TABLE_SCHEMA=='invenage',]
tmp <- tmp %>% select(TABLE_NAME,COLUMN_NAME,COLUMN_TYPE)

# check for columns that are not consistent in database
# first generate a dataframe containing unique combination of column name and type
tmp2 <- tmp[!duplicated(tmp %>% select(COLUMN_NAME, COLUMN_TYPE)),]

# in this data frame, if a column name is duplicated, it indicate that this 
# column name has multiple type
if(nrow(tmp2[duplicated(tmp2$COLUMN_NAME),])){
  print(tmp2[duplicated(tmp2$COLUMN_NAME),])
}
```

### Packaging

- Entries with null or blank unit

```{r packaging_check1,echo=F,message=F,warning=F}
packaging <- db_read_query("select * from packaging")
test <- packaging[is.na(packaging$unit)|packaging$unit=='',]
if(nrow(test)>0){
  print(test)
}else{print('check ok')}
```

- packaging that does not have linked product

```{r packaging_check2,echo=F,message=F,warning=F}
test <- db_read_query("select * from packaging left join product_info 
                      on packaging.prod_code = product_info.prod_code
                      where product_info.comm_name is null")
test <- packaging[is.na(packaging$unit)|packaging$unit=='',]
if(nrow(test)>0){
  print(test)
}
```


### sale_log check

- sale that does not have valid packaging

```{r sale_log_check1}
test <- db_read_query("select * from sale_log left join packaging 
                      on sale_log.prod_code = packaging.prod_code
                      where packaging.units_per_pack is null")
```

```{r sale_log_check2}
test2 <- merge(import_log,packaging,all.x=T)
test[is.na(test$units_per_pack),]

test <- db_read_query("select * from sale_log left join product_info 
                      on sale_log.prod_code = product_info.prod_code
                      where product_info.comm_name is null")

```

### product_info with vendor_id=0

```{r prod_vendor_id_check}
kable(db_read_query("select * from product_info where vendor_id = 0"))

```
